[package]
name = "mad-turmoil"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "madsim-inspired determinism for turmoil-based simulation tests"

[dependencies]
libc = "0.2"
rand = "0.8"
tokio = "1"
turmoil = "0.6"
